language: go
go: stable
cache:
  directories:
  - $GOPATH/pkg/mod
services:
- docker
env:
  global:
  - GO111MODULE=on
jobs:
  include:
  - name: Test with Go stable
  - name: Lint with errcheck
    script:
    - go get -v github.com/kisielk/errcheck
    - errcheck ./...
  - name: Build Docker container
    install: skip
    script: docker build .
