language: go
go: stable
cache:
  directories:
  - $GOPATH/pkg/mod
services:
- docker
env:
  global:
  - GO111MODULE=on
jobs:
  include:
  - name: Test Go stable
  - name: Lint errcheck, golint, staticcheck
    before_script:
    - go get -v github.com/kisielk/errcheck golang.org/x/lint/golint
    - sudo curl -L https://github.com/dominikh/go-tools/releases/download/2019.1/staticcheck_linux_amd64 -o /usr/bin/staticcheck
    - sudo chmod +x /usr/bin/staticcheck
    script:
    - errcheck ./...
    - golint -set_exit_status ./...
    - staticcheck ./...
  - name: Build Docker container
    install: skip
    script: docker build .
