language: go
cache:
  directories:
  - $GOPATH/pkg/mod
services:
- docker

env:
  global:
  - GO111MODULE=on
matrix:
  include:
  - go: 1.11.x
    env: COMMAND='go test -v ./...'
  - go: master
    env: COMMAND='go test -v ./...'
  - env: COMMAND='docker build .'

script: $COMMAND
